# Site settings
title: Anandu B Ajith
email: reach2anandu@gmail.com
author: Anandu B Ajith
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/anandu.net/" # the base hostname & protocol for your site
twitter: anandubajith
github_username:  jekyll
permalink: /posts/:title
domain: anandu.net
# Build settings
markdown: kramdown
